### ISSUE TITLE
postback with regex or wildcard or parameter

### ISSUE THREAD

**Issue by adavid102** [Charca/bootbot#10]
Hi,
First, thanks for this Awesome library.
I'm using it and enjoying every moment.

I brought up a pretty nice project of my own.
I now ran into an issue where I have a list of items with buttons.
I want to define a postback so that when the user presses one of the buttons I will arrive at the same function and handle same just with different parameter.
Can you help to recommend how to easily solve this?

Should I use postback with regex?  If so, how?

Thanks.

**Comment by Charca** [comment]
Hey @adavid102, thanks so much for the comments!

If I understood correctly, you have a series of buttons with postbacks that differ in some sort of ID or param, and you want to handle all of them with a single function, right? So something like this:

- BUTTON_ID_123
- BUTTON_ID_456
- BUTTON_ID_789

The `.on()` method doesn't accept a regex because of how the EventEmitter class works, but you can workaround this by listening for the global `postback` event and then matching the URL inside that function:

```javascript
bot.on('postback', (payload, chat) => {
  const re = /BUTTON_ID_(\d+)/i;
  const buttonPayload = payload.postback.payload;
  const match = buttonPayload.match(re);
  
  if (match) {
    const buttonId = match[1];
    
    // Do something with buttonId
  }
});
```

Let me know if this works for you.

**Comment by adavid102** [comment]
Thanks so much for you reply
I tried somethink similar but used bot.on('message', (payload, chat) instead of bot.on('postback', (payload, chat) ..  :-)
Tried your solution and it works.
You're bootbot library is truly amazing.
Saved me probably weeks of work..
