### ISSUE TITLE
Initialize Bootbot without needing app secret [Feature Request]

### ISSUE THREAD

**Issue by jannavarro** [Charca/bootbot#18]
It would be good to find a way to do initialize Bootbot without needing app secret. I'm finding a way where I can put my code that uses Bootbot in github. 

In Messenger bot [setup](https://developers.facebook.com/docs/graph-api/webhooks#setupget) it says nodejs needs a GET method for Facebook verification. I'm not sure if inside Bootbot constructor we can just setup an app.get('/webhook/', function (req, res)... method. Is this possible? Some samples use something like this:

```
app.get('/webhook/', function (req, res) {
    if (req.query['hub.verify_token'] === 'some_token') {
        res.send(req.query['hub.challenge'])
    }
    res.send('Error, wrong token')
})
```

**Comment by pferdefleisch** [comment]
The way I get around this is to use environmental variables for my secrets, and not committing my secrets file. I have been using this https://github.com/goliatone/envset but there are quite a few alternatives.

The app secret [is very important for security](https://chatbotsmagazine.com/how-to-kill-a-bot-with-10-http-requests-ca7eb57c2ad1#.jf6hjj7hn) and I believe making it optional is a mistake, especially with many safer and portable solutions.

**Comment by jannavarro** [comment]
@pferdefleisch I'll use those options as an alternative. I just raised this issue since other messenger bot tutorials like [this](https://github.com/jw84/messenger-bot-tutorial) does not need app secret. I'm not sure why Bootbot needs the app secret instead of using the sample code I posted in the question. What's the reason why Bootbot needs the app secret while other samples show that we can make bots without providing it?

**Comment by pferdefleisch** [comment]
@jannavarro 
The reason for asking for the app secret is that Facebook signs all of the requests using the payload they send to you hashed with your app secret. This makes it so a bad actor finds your endpoint, they can't just spoof requests, pretending to be Facebook and [as shown in this link](https://chatbotsmagazine.com/how-to-kill-a-bot-with-10-http-requests-ca7eb57c2ad1#.jf6hjj7hn), DOSing you or sending your users malicious messages (phishing, etc).

I was a bit cautious when I had to give my app secret for bootbot when the other frameworks didn't ask for it, but after looking through the code a bit I was less freaked out. And it turns out _the other folks are doing it wrong_. Read the article and you will understand the usefulness of this.

And have fun bootbotting ❤️ 🤖 !

**Comment by jannavarro** [comment]
@pferdefleisch Thanks for the taking the time to explain things. I understand its use now.
