### ISSUE TITLE
Doubt about workflow using the bootbot-cli.

### ISSUE THREAD

**Issue by brenohq** [Charca/bootbot#21]
Hello, I am a beginner in chatbots development and a friend recommended me the [bootbot](https://github.com/Charca/bootbot) framework, I really liked it! I also found [this CLI](https://github.com/Charca/bootbot-cli), but I am in doubt about how I will develop using it.

I need to run **bootbot start** every time I change a file?
I need to run **bootbot start** together with **nodemon index.js**?
I need to run set up my webhook URLs every time I start developing?

I'm asking these questions because I ran the project using both ways, but sometimes I felt a delay between the commands on my machine and noticed the bot working in Messenger, so I could not identify where the errors were and even know If there was any mistake or the project was not online.

And congratulations for the brilliant work! @Charca @pferdefleisch

**Comment by Charca** [comment]
Hey @brenohq, I'm glad you're liking BootBot so far!

To answer your question, you only need to run `bootbot start` once and leave that terminal window open. That command will run `nodemon` under the hood so you don't need to run it yourself. Also, once you created your project and you've setup your webhook URLs once, there's no need to change them. Every time you run `bootbot start` in the same project, it will give you the same webhook URL, so no need to change there.

If you notice a delay is because it usually takes a few seconds for your local server to update, and the communication between Messenger and the server is slower than usual because it's using your computer instead of an actual server in the cloud. This delay will of course go away once you deploy your app to production. If the delay you notice is more than a few seconds, please let me know and I'll investigate.

Thanks for your support, and let me know if you have any other questions!

**Comment by brenohq** [comment]
Thanks for the answer @Charca ! I do not know if this is the best place to ask questions about development, maybe it's better to create a gitter or facebookgroup. There is already a place for it? Thank you so much!

**Comment by Charca** [comment]
Hey @brenohq, I've just created a Slack channel for the group. It's just me for now, but I'll add the link to the README so hopefully more people will join in the future :)

Here's the invite link: https://bootbot.slack.com/shared_invite/MTQwODA0MDU2NDUxLTE0ODcwMTQ1MjgtNTc3MDVhOWRjZQ
