### ISSUE TITLE
How can we integrate NLP with this framework ?

### ISSUE THREAD

**Issue by deepakmhr** [Charca/bootbot#32]
I want to integrate LUIS with this framework, Is there any way to integrate NLP ?

**Comment by pferdefleisch** [comment]
A few suggestions:

- LUIS works out of the box with microsoft bot framework. You could use that instead of bootbot
- Instead of LUIS, you could use [wit.ai](https://wit.ai) and this client [BeepBoopHQ/witbot](https://github.com/BeepBoopHQ/witbot)
- You could read the source of witbot and build your own LUIS client for bootbot
- you can write express middlewares for bootbot and you may be able to figure out how to integrate something like this https://github.com/Stevenic/botkit-middleware-luis

**Comment by Drag0s** [comment]
Any suggestion for API.AI?

**Comment by dragGH102** [comment]
I'm also interested in the API.ai thing

**Comment by mraaroncruz** [comment]
There's the [node dialogflow (formerly api.ai) client](https://github.com/dialogflow/dialogflow-nodejs-client) which has a bunch of examples of how to use it [here](https://github.com/dialogflow/dialogflow-nodejs-client/tree/master/samples)

But facebook supports wit.ai natively now, either by just guessing or you can add your wit.ai api key in the messenger tab in https://developers.facebook.com.
Your messages now come with a `{"nlp": {"intent": ....}}` or something if you have it switched on.

I did something for a test here.
```js
const MIN_CONFIDENCE = 0.6;

const getIntent = (message) => {
  const {intent} = message.nlp.entities;
  if (intent) {
    const intents = intent.filter((it) => it.confidence > MIN_CONFIDENCE)
    if (intents.length > 0) {
      return intents[0].value;
    } else {
      return null;
    }
  } else {
    return null;
  }
};

bot.on('message', (payload, chat) => {
  const intent = getIntent(payload.message);
  handleIntent(intent, payload, chat);
});
```
Where `handleIntent` switches on the intent value and does something.

You just have to switch it on and you're good to go. 
Pretty cool.

**Comment by mraaroncruz** [comment]
I'm going to close this since we now have wit.ai built in. I will add an issue to expose the native wit.ai stuff in a sugar coated way. Ok. I added it [here](https://github.com/Charca/bootbot/issues/85)
