### ISSUE TITLE
[Question] Difference between bootbot and botkit

### ISSUE THREAD

**Issue by xJeremie** [Charca/bootbot#35]
I planning to develop new bot, but I'm confused between using `bootbot` and `botkit`. Can you tell me the difference between 2 frameworks, so I can confident invest time on it?

**Comment by pferdefleisch** [comment]
I started using bootbot because it is Messenger focussed, which I am too.
There is some nice sugar for using Messenger [see methods from here on](https://github.com/Charca/bootbot#sendtextmessage).

Botkit is multi-platform, but you give a lot of these niceties up. The examples for using Messenger aren't great and it feels like a second class citizen compared to Slack. But if you want a multi-platform bot, it may be a better choice for you.

IMO, if you are planning on just supporting Messenger, bootbot is great. If you want to support multi-platform from day one, check out botkit and see what you think.

**Comment by Charca** [comment]
Hey @xJeremie,

Just to add a bit more info to @pferdefleisch's great explanation, in terms of framework capabilities there's not a big difference between the two (except that BootBot only works with Messenger, of course). You'll be able to accomplish anything you want to do with your bot no matter which framework you choose; I just think that BootBot's API is cleaner and easier to maintain, but that might be just personal preference.

I'd recommend that you take a look at examples of bots built with both frameworks and compare its APIs, it all comes down to that.

I'm closing this issue but feel free to keep discussing.
