### ISSUE TITLE
composer_input_disabled not working

### ISSUE THREAD

**Issue by aramiscubillo** [Charca/bootbot#49]
Hi, I'm trying to disable user input in my bot, but it doesn't seams to work. Here is my persistent menu setup code:

```
bot.setPersistentMenu(
[
    {
      "locale":"default",
      "call_to_actions":[
        {
          "type":"postback",
          "title":"Español",
          "payload":"ES"
        },
		{
          "type":"postback",
          "title":"English",
          "payload":"EN"
        }
      ]
    },
    {
      "locale":"zh_CN",
      "composer_input_disabled":false
    }
  ]
, true);
```

All the bot interaction will be made with quickreplies and the persistent menu to set the language.

Regards

**Comment by mraaroncruz** [comment]
Maybe the issue is a double negative problem? You have it set to `disabled = false` or `enabled`.
If this is just a typo, it may be a menu caching problem which Messenger is infamous for. Either delete your chat and try again (if your bot is not "live") or patiently wait.
The format of your data is correct.

**Comment by mraaroncruz** [comment]
Closing due to no response
